### ISSUE TITLE
Плагин для привязки сайт-сервер

### ISSUE THREAD

**Issue by TOWUK** [EpicStep/EpicCMS#9]
Привет, планируется ли создание плагина для сайта? если планируеься в будущем группы то будет прекрасно иметь 1 ваш плагин чем пермишены и authMe с кривой поддерждкой одной БД.

**Comment by EpicStep** [comment]
Привет, у меня была идея создания плагина, но я не особо умею писать на Java, был бы рад поддержке сообщества в реализации.

**Comment by TOWUK** [comment]
> Привет, у меня была идея создания плагина, но я не особо умею писать на Java, был бы рад поддержке сообщества в реализации.

Понял, спасибо за ответ, к сожалению сам не силен в программировании поэтому не смогу помочь :(

**Comment by EpicStep** [comment]
> > Привет, у меня была идея создания плагина, но я не особо умею писать на Java, был бы рад поддержке сообщества в реализации.
> 
> Понял, спасибо за ответ, к сожалению сам не силен в программировании поэтому не смогу помочь :(

Да, без проблем, может в будущем напишу, если время и желание будет.
